// GENERATED by tools/build_types.mjs from eip681.mjs + deriveEip681.mjs — do not edit.
// Regenerate with: npm run build:types
//
// EIP-681 payment-request URI parser, validator and formatter. Zero dependencies.

/** A parse error or warning. `code` is the stable identifier to branch on;
 *  `message` is for humans and may change between releases. */
export interface Diagnostic {
  code: string;
  message: string;
}

export interface AmountParseResult {
  ok: boolean;
  /** Exact base units. `null` unless `ok` is true. */
  value: bigint | null;
  errors: Diagnostic[];
}

export interface ParseResult {
  /** True when there are no `errors`. `warnings` may still be present and do not
   *  affect `ok` — they mark inputs that are valid but unsafe to hand to a
   *  third-party parser. */
  ok: boolean;
  scheme: string | null;
  /** Payment target: the address, or the ERC-20 contract for a token transfer. */
  target: string | null;
  chainId: number | null;
  functionName: string | null;
  params: Record<string, string>;
  /** True only for the ERC-20 `transfer` function. An `approve` is not a payment. */
  isTokenTransfer: boolean;
  /** The payee. For a token transfer this is the `address=` parameter, never the
   *  contract. Kept separate from `target` on purpose. */
  recipient: string | null;
  /** Exact base units, or `null`. **Never non-null when `ok` is false:** branch on
   *  `ok`, never on this field, or a failed parse could be paid. */
  amount: bigint | null;
  errors: Diagnostic[];
  warnings: Diagnostic[];
  canonical: string | null;
}

/** The shape `format()` accepts — a parsed value, or a hand-built equivalent. */
export interface CanonicalInput {
  target: string;
  chainId?: number | null;
  functionName?: string | null;
  params?: Record<string, string>;
}

export interface Erc20TransferRequest {
  chainId?: number | null;
  /** The ERC-20 contract address. */
  token: string;
  /** The payee. */
  to: string;
  /** Exact base units. */
  amount: bigint | string | number;
}

export interface NativeTransferRequest {
  chainId?: number | null;
  to: string;
  /** Exact wei. */
  wei: bigint | string | number;
}

/** `{ ok: true, errors: [], uri }` on success; `{ ok: false, errors, uri: null }`
 *  on failure — a failed build never hands back a URI to sign. */
export interface BuildResult {
  ok: boolean;
  errors: Diagnostic[];
  uri: string | null;
}

export const ERC20_TRANSFER: string;
export const SCHEME: string;
export function deriveEip681(invoice: unknown): string | null;
export function erc20Transfer(req: Erc20TransferRequest): BuildResult;
export function format(v: CanonicalInput): string;
export function isChecksumAddress(addr: string): boolean;
export function isHexAddress(s: unknown): boolean;
export function isUsableAddress(s: unknown): boolean;
export function keccak256(bytes: Uint8Array): Uint8Array;
export function nativeTransfer(req: NativeTransferRequest): BuildResult;
export function parse(uri: string): ParseResult;
export function parseAmount(raw: string): AmountParseResult;
export function toBaseUnits(value: string | number | bigint, decimals: number): bigint;
export function toChecksumAddress(addr: string): string;
