// tools/build_types.mjs
//
// Generates index.d.ts and index.mjs from the real public surface of the kit.
//
//   node tools/build_types.mjs
//
// Why generate instead of hand-write: a hand-maintained .d.ts drifts the moment the
// parser changes, and a drifting .d.ts is worse than none — it lets a TypeScript
// consumer's build succeed while their runtime breaks. This script reads the actual
// export statements and FAILS LOUDLY on any export it has no type for, so drift is a
// build error rather than a silent lie.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Every module whose exports are part of the public surface. */
const MODULES = ['eip681.mjs', 'deriveEip681.mjs'];

// --- the declared type for each export --------------------------------------
// Any export not in this table aborts the build. That is the drift alarm.
const TYPES = {
  // eip681.mjs
  SCHEME: 'export const SCHEME: string;',
  ERC20_TRANSFER: 'export const ERC20_TRANSFER: string;',
  keccak256: 'export function keccak256(bytes: Uint8Array): Uint8Array;',
  toChecksumAddress: 'export function toChecksumAddress(addr: string): string;',
  isChecksumAddress: 'export function isChecksumAddress(addr: string): boolean;',
  parseAmount: 'export function parseAmount(raw: string): AmountParseResult;',
  parse: 'export function parse(uri: string): ParseResult;',
  format: 'export function format(v: CanonicalInput): string;',
  erc20Transfer: 'export function erc20Transfer(req: Erc20TransferRequest): BuildResult;',
  nativeTransfer: 'export function nativeTransfer(req: NativeTransferRequest): BuildResult;',
  // deriveEip681.mjs
  deriveEip681: 'export function deriveEip681(invoice: unknown): string | null;',
  toBaseUnits: 'export function toBaseUnits(value: string | number | bigint, decimals: number): bigint;',
  isHexAddress: 'export function isHexAddress(s: unknown): boolean;',
  isUsableAddress: 'export function isUsableAddress(s: unknown): boolean;',
};

/** Modules that must be re-exported, with the names taken from each (explicitly, so
 *  that a name present in both files cannot silently shadow the other). */
const ENTRY = [
  { file: './eip681.mjs', names: ['SCHEME', 'ERC20_TRANSFER', 'keccak256', 'toChecksumAddress',
      'isChecksumAddress', 'parseAmount', 'parse', 'format', 'erc20Transfer', 'nativeTransfer'] },
  { file: './deriveEip681.mjs', names: ['deriveEip681', 'toBaseUnits', 'isHexAddress', 'isUsableAddress'] },
];

// --- discover the real export names per module -------------------------------
const found = new Map(); // module -> Set(name)
for (const file of MODULES) {
  const src = readFileSync(join(root, file), 'utf8');
  const names = new Set();
  for (const m of src.matchAll(/^export\s+(?:async\s+)?function\s+([A-Za-z0-9_$]+)/gm)) names.add(m[1]);
  for (const m of src.matchAll(/^export\s+(?:const|let|var)\s+([A-Za-z0-9_$]+)/gm)) names.add(m[1]);
  for (const m of src.matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const part of m[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/).pop().trim();
      if (name) names.add(name);
    }
  }
  found.set(file, names);
}

const allNames = new Set([...found.values()].flatMap((s) => [...s]));
const missing = [...allNames].filter((n) => !(n in TYPES));
if (missing.length) {
  console.error('BUILD FAILED: public exports with no declared type:');
  for (const n of missing) console.error('  ' + n);
  console.error('\nAdd them to TYPES in tools/build_types.mjs before shipping a .d.ts,');
  console.error('otherwise consumers get types that silently disagree with runtime.');
  process.exit(1);
}

// Every name the entry point claims must actually exist, or the entry point is a lie.
for (const { file, names } of ENTRY) {
  const have = found.get(file.replace('./', '')) || new Set();
  const bad = names.filter((n) => !have.has(n));
  if (bad.length) {
    console.error(`BUILD FAILED: entry point re-exports names absent from ${file}: ${bad.join(', ')}`);
    process.exit(1);
  }
}

const header = `// GENERATED by tools/build_types.mjs from eip681.mjs + deriveEip681.mjs — do not edit.
// Regenerate with: npm run build:types
//
// EIP-681 payment-request URI parser, validator and formatter. Zero dependencies.

/** A parse error or warning. \`code\` is the stable identifier to branch on;
 *  \`message\` is for humans and may change between releases. */
export interface Diagnostic {
  code: string;
  message: string;
}

export interface AmountParseResult {
  ok: boolean;
  /** Exact base units. \`null\` unless \`ok\` is true. */
  value: bigint | null;
  errors: Diagnostic[];
}

export interface ParseResult {
  /** True when there are no \`errors\`. \`warnings\` may still be present and do not
   *  affect \`ok\` — they mark inputs that are valid but unsafe to hand to a
   *  third-party parser. */
  ok: boolean;
  scheme: string | null;
  /** Payment target: the address, or the ERC-20 contract for a token transfer. */
  target: string | null;
  chainId: number | null;
  functionName: string | null;
  params: Record<string, string>;
  /** True only for the ERC-20 \`transfer\` function. An \`approve\` is not a payment. */
  isTokenTransfer: boolean;
  /** The payee. For a token transfer this is the \`address=\` parameter, never the
   *  contract. Kept separate from \`target\` on purpose. */
  recipient: string | null;
  /** Exact base units, or \`null\`. **Never non-null when \`ok\` is false:** branch on
   *  \`ok\`, never on this field, or a failed parse could be paid. */
  amount: bigint | null;
  errors: Diagnostic[];
  warnings: Diagnostic[];
  canonical: string | null;
}

/** The shape \`format()\` accepts — a parsed value, or a hand-built equivalent. */
export interface CanonicalInput {
  target: string;
  chainId?: number | null;
  functionName?: string | null;
  params?: Record<string, string>;
}

export interface Erc20TransferRequest {
  chainId?: number | null;
  /** The ERC-20 contract address. */
  token: string;
  /** The payee. */
  to: string;
  /** Exact base units. */
  amount: bigint | string | number;
}

export interface NativeTransferRequest {
  chainId?: number | null;
  to: string;
  /** Exact wei. */
  wei: bigint | string | number;
}

/** \`{ ok: true, errors: [], uri }\` on success; \`{ ok: false, errors, uri: null }\`
 *  on failure — a failed build never hands back a URI to sign. */
export interface BuildResult {
  ok: boolean;
  errors: Diagnostic[];
  uri: string | null;
}
`;

const decls = [...allNames]
  .filter((n) => n in TYPES)
  .sort()
  .map((n) => TYPES[n])
  .join('\n');

const dts = `${header}\n${decls}\n`;
writeFileSync(join(root, 'index.d.ts'), dts, 'utf8');

const entry = `// Public entry point. Re-exports the whole kit as one module.
// Types live in index.d.ts alongside this file.
${ENTRY.map(({ file, names }) => `export { ${names.join(', ')} } from '${file}';`).join('\n')}
`;
writeFileSync(join(root, 'index.mjs'), entry, 'utf8');

console.log(`modules scanned: ${MODULES.join(', ')}`);
console.log(`public exports: ${[...allNames].sort().join(', ')}`);
console.log(`wrote index.d.ts (${dts.length} bytes) and index.mjs`);
if (missing.length === 0) {
  const covered = [...allNames].filter((n) => n in TYPES).length;
  console.log(`type coverage: ${covered}/${allNames.size} — every export declared`);
}
